name: domainproxy
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple Dynamic Reverse Proxy
description: |
  Domainproxy is a simple reverse proxy that will proxy an entire domain to a single backend. Similar to the way virtual hosts might work.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


parts:
  domainproxy:
    go-packages: [github.com/ryanjyoder/domainproxy/cmd/domainproxy]
    plugin: go


apps:
  domainproxy:
    command: domainproxy
    daemon: simple
